version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: setuptools
    versions:
    - "> 50.3.2"
  - dependency-name: pip
    versions:
    - "> 20.3"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99