sudo: required
services: docker
dist: bionic
group: edge
language: ruby
addons:
    apt:
        sources:
            - sourceline: "deb http://deb.debian.org/debian sid main contrib non-free"
              key_url: "https://ftp-master.debian.org/keys/archive-key-9.asc"
        packages:
            - debootstrap
branches:
    only:
        - master
        - develop
env:
    global:
        # Docker Hub username ${DH_USERNAME}
        - DH_USERNAME="luisalejandro"
        # Docker Hub password ${DH_PASSWORD}
        - secure: "SOMNzEN3nwNYiw9K1LCpL55umU7K+4fEtbHdVZNm3pZ5ejgjXxsKxMduUt1ZHopfkmbW77ejMgmKieDRC/QJbIngcaENoP/vNsL3/6VcCScy3pXtS76svOl6+jLRBuvR3xVTQ6BvZwDtK1gozjlDmvvlzzoC2zF4KFHtr/G8BE5iOymv+TsWWS0ReL1NrMI2QAXOZjRI0mShCtaMjFo2/rphdex/GB2Nq6h3pXyi0witQTjb4FrryTpG3Y39tyFVFo1TUJrJPAdL0t9TFQ1asxJXafPfoxd4rGoOW96hbZu8Q0goQoMxs5lYj+4i5HJWq72O5G849KqOa9LH9t9aj7s4ZJBLVccrn0Ksl9rbcEIl0STz5E4Iy9HJHIWiIIwg0tb2/gFNyAMx/7UpybFSpOlTvW+ELZ2vmgbtOVP+eN5Ir5FRNf4vfbtslutLc7thFsomvGUKuRy1tH4HxminFduIwtX0McRlF4UKozS1J3KZ0Y8NRylAWWsBRrlkPDBbDYf+hAKtJsJuvk0/Dau1mSq1JMYMmXna5Qvm5qcXCLx1N0d9/YCzNDwNpExpBHyP3EQwpOqwcR3P/pQr/YXbA69cO/nI1Gf14U2KlfZ0OOMN13WzxJ/nQ7Eeyu8XynFRkggYY0tJEBO+MMJY+EGLSBadkze4KB2Qs+9eL4iPuFE="
    matrix:
        - DOCKER_IMAGE_NAME="dockershelf/debian:stretch" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/debian:oldstable" DEBIAN_SUITE="oldstable"
        - DOCKER_IMAGE_NAME="dockershelf/debian:buster" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/debian:stable" DEBIAN_SUITE="stable"
        - DOCKER_IMAGE_NAME="dockershelf/debian:bullseye" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/debian:testing" DEBIAN_SUITE="testing"
        - DOCKER_IMAGE_NAME="dockershelf/debian:sid" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/debian:unstable dockershelf/debian:latest" DEBIAN_SUITE="unstable"
        - DOCKER_IMAGE_NAME="dockershelf/latex:basic" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/latex:latest"
        - DOCKER_IMAGE_NAME="dockershelf/latex:full"
        - DOCKER_IMAGE_NAME="dockershelf/python:2.7" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/python:2"
        - DOCKER_IMAGE_NAME="dockershelf/python:3.5"
        - DOCKER_IMAGE_NAME="dockershelf/python:3.6"
        - DOCKER_IMAGE_NAME="dockershelf/python:3.8" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/python:3"
        - DOCKER_IMAGE_NAME="dockershelf/python:3.9" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/python:latest"
        - DOCKER_IMAGE_NAME="dockershelf/ruby:2.1"
        - DOCKER_IMAGE_NAME="dockershelf/ruby:2.3"
        - DOCKER_IMAGE_NAME="dockershelf/ruby:2.5"
        - DOCKER_IMAGE_NAME="dockershelf/ruby:2.7" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/ruby:latest"
        - DOCKER_IMAGE_NAME="dockershelf/node:8"
        - DOCKER_IMAGE_NAME="dockershelf/node:9"
        - DOCKER_IMAGE_NAME="dockershelf/node:10"
        - DOCKER_IMAGE_NAME="dockershelf/node:11"
        - DOCKER_IMAGE_NAME="dockershelf/node:12"
        - DOCKER_IMAGE_NAME="dockershelf/node:13"
        - DOCKER_IMAGE_NAME="dockershelf/node:14" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/node:latest"
        - DOCKER_IMAGE_NAME="dockershelf/mongo:3.6"
        - DOCKER_IMAGE_NAME="dockershelf/mongo:4.0"
        - DOCKER_IMAGE_NAME="dockershelf/mongo:4.2"
        - DOCKER_IMAGE_NAME="dockershelf/mongo:4.4" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/mongo:latest"
        - DOCKER_IMAGE_NAME="dockershelf/postgres:9.6"
        - DOCKER_IMAGE_NAME="dockershelf/postgres:10"
        - DOCKER_IMAGE_NAME="dockershelf/postgres:11"
        - DOCKER_IMAGE_NAME="dockershelf/postgres:12"
        - DOCKER_IMAGE_NAME="dockershelf/postgres:13" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/postgres:latest"
        - DOCKER_IMAGE_NAME="dockershelf/odoo:11.0"
        - DOCKER_IMAGE_NAME="dockershelf/odoo:12.0"
        - DOCKER_IMAGE_NAME="dockershelf/odoo:13.0" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/odoo:latest"
        - DOCKER_IMAGE_NAME="dockershelf/php:7.0"
        - DOCKER_IMAGE_NAME="dockershelf/php:7.2"
        - DOCKER_IMAGE_NAME="dockershelf/php:7.3"
        - DOCKER_IMAGE_NAME="dockershelf/php:7.4" DOCKER_IMAGE_EXTRA_TAGS="dockershelf/php:latest"
install:
    - gem install docker-api serverspec
before_script:
    - |
        if [ "${TRAVIS_BRANCH}" == "develop" ]; then
            DOCKER_IMAGE_TARGET="${DOCKER_IMAGE_NAME##dockershelf/}"
            sed -i -r 's|FROM\s*(.*?)|FROM \1-dev|g' "${DOCKER_IMAGE_TARGET/://}/Dockerfile"
            sed -i -r 's|FROM scratch-dev|FROM scratch|g' "${DOCKER_IMAGE_TARGET/://}/Dockerfile"
        fi
    - bash build-image.sh "${DOCKER_IMAGE_NAME}" "${DEBIAN_SUITE}"
script:
    - bash test-image.sh "${DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_EXTRA_TAGS}"
after_success:
    - |
        if [ "${TRAVIS_BRANCH}" == "develop" ]; then
            docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_NAME}-dev
            DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME}-dev"
        fi
    - bash push-image.sh ${DOCKER_IMAGE_NAME} ${DH_USERNAME} ${DH_PASSWORD}
    - |
        if [ -n "${DOCKER_IMAGE_EXTRA_TAGS}" ]; then
            for EXTRA_TAG in ${DOCKER_IMAGE_EXTRA_TAGS}; do
                if [ "${TRAVIS_BRANCH}" == "develop" ]; then
                    EXTRA_TAG="${EXTRA_TAG}-dev"
                fi
                docker tag ${DOCKER_IMAGE_NAME} ${EXTRA_TAG}
                bash push-image.sh ${EXTRA_TAG} ${DH_USERNAME} ${DH_PASSWORD}
            done
        fi
